version: '3.8'

services:
  frontend:
    build: ./ems-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:8080
    command: npm run dev -- --host

  backend:
    build: ./ems-backend
    ports:
      - "8080:8080"

